#!/usr/bin/env python3
"""One-command North Avant / Bartlesville HEC workflow.

Current physical tags
---------------------
* Tag-only HEC: material 5.
* Injection borehole: material 6, vertical cylinder.
* Strainmeter sensor pods: AVN2, AVN87, and AVN31, materials 7--9.

The active local targets are read from ``bartlesville_hec_geometry.json``
after the PLC builder runs. This prevents a downstream mismatch when sensor
locations or the number of strainmeters change.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Iterable, List, Sequence

# Update only these paths if your local installation differs.
TETGEN_EXE = os.environ.get(
    "TETGEN_EXE",
    "/home/kwesi/Tetgen/build/tetgen",
)

VORONOI_EXE = os.environ.get(
    "VORONOI_EXE",
    "/home/kwesi/voronoi/src/voronoi",
)


MESH_NAME = "bartlesville_hec"
SCRIPT_DIR = Path(__file__).resolve().parent
TETGEN_DIAGNOSE = False
SKIP_PX = False
KEEP_OLD_OUTPUTS = False
MAX_TETRAHEDRA = int(os.environ.get("BARTLESVILLE_MAX_TETS", "900000"))

BASE_VSET_FILES: List[str] = [
    "top.vset",
    "bottom.vset",
    "north.vset",
    "south.vset",
    "east.vset",
    "west.vset",
    "overburden.vset",
    "bartlesville_sand.vset",
    "basal_layer.vset",
    "underburden.vset",
    "hec.vset",
]
UNION_VSET_FILES: List[str] = [
    "refined_targets.vset",
    "sensor_pods.vset",
    "strainmeter_sensors.vset",
    # Compatibility names retained by the updated tagger.
    "strainmeter_boreholes.vset",
    "boreholes.vset",
]
# Delete obsolete vsets generated by older 4-strainmeter layouts as part of a
# clean run.  These are not used in the new workflow.
OBSOLETE_VSET_FILES: List[str] = [
    "strainmeter_1.vset",
    "strainmeter_2.vset",
    "strainmeter_3.vset",
    "strainmeter_4.vset",
    "injection_well.vset",
    "wellbore.vset",
    "hec_surface.vset",
]

REQUIRED_HELPERS: List[str] = [
    "build_poly_layers4.py",
    "layers4_get_material_boundary_tags.py",
    "tetgen_to_avs.py",
    "material_h5_from_txt.py",
    "convert_vset_to_ex.py",
    "generate_ugi.py",
    "mapping.py",
]


def nonempty(path: Path, min_bytes: int = 1) -> bool:
    return path.is_file() and path.stat().st_size >= min_bytes


def require_executable(path_text: str, label: str) -> Path:
    path = Path(path_text).expanduser()
    if not path.is_file():
        raise FileNotFoundError(f"{label} executable was not found: {path}")
    if not os.access(path, os.X_OK):
        raise PermissionError(f"{label} is not executable: {path}")
    return path


def require_helpers() -> None:
    missing = [name for name in REQUIRED_HELPERS if not (SCRIPT_DIR / name).is_file()]
    if missing:
        raise FileNotFoundError("Missing helper scripts:\n  " + "\n  ".join(missing))


def run(command: Iterable[object]) -> None:
    values = [str(value) for value in command]
    print("[CMD]", " ".join(values))
    subprocess.run(values, check=True)


def run_voronoi(command: Iterable[object], log_path: Path) -> None:
    values = [str(value) for value in command]
    print("[CMD]", " ".join(values))
    result = subprocess.run(
        values,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    log_path.write_text(result.stdout or "", encoding="utf-8")
    if result.stdout:
        print(result.stdout, end="" if result.stdout.endswith("\n") else "\n")
    if result.returncode != 0:
        raise RuntimeError(f"VORONOI failed with exit code {result.returncode}. See {log_path.name}.")


def normalize_tetgen_ascii(path: Path) -> None:
    """Remove TetGen comments for legacy helper scripts that require line-one headers."""
    if not path.is_file():
        return
    kept: List[str] = []
    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if line and not line.startswith("#"):
                kept.append(line + "\n")
    if not kept:
        raise RuntimeError(f"No numeric TetGen data found in {path}")
    path.write_text("".join(kept), encoding="utf-8")
    print(f"    normalized {path.name}")


def first_numeric_header_count(path: Path) -> int:
    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if line and not line.startswith("#"):
                return int(line.split()[0])
    raise RuntimeError(f"No numeric header in {path}")


def write_mesh_count_summary() -> tuple[int, int]:
    node_file = SCRIPT_DIR / f"{MESH_NAME}.1.node"
    ele_file = SCRIPT_DIR / f"{MESH_NAME}.1.ele"
    nodes = first_numeric_header_count(node_file)
    tetrahedra = first_numeric_header_count(ele_file)
    output = SCRIPT_DIR / f"{MESH_NAME}_mesh_counts.txt"
    output.write_text(
        "quantity,count\n"
        f"nodes,{nodes}\n"
        f"tetrahedra,{tetrahedra}\n"
        f"postprocess_tet_limit,{MAX_TETRAHEDRA}\n",
        encoding="utf-8",
    )
    print(f"    nodes      : {nodes:,}")
    print(f"    tetrahedra : {tetrahedra:,}")
    print(f"    guard      : {MAX_TETRAHEDRA:,}")
    return nodes, tetrahedra


def load_target_vsets() -> List[str]:
    """Read active target names from the new geometry JSON and return vset names."""
    geometry_path = SCRIPT_DIR / f"{MESH_NAME}_geometry.json"
    if not geometry_path.is_file():
        raise FileNotFoundError(f"Missing geometry JSON after PLC build: {geometry_path.name}")
    geometry: dict[str, Any] = json.loads(geometry_path.read_text(encoding="utf-8"))
    targets = geometry.get("refinement_targets", [])
    if not isinstance(targets, list) or not targets:
        raise RuntimeError("Geometry JSON does not contain a non-empty refinement_targets list.")

    names: List[str] = []
    for target in targets:
        name = str(target.get("name", "")).strip()
        if not name:
            raise RuntimeError("A refinement target in the geometry JSON has no name.")
        # vset output is placed in SCRIPT_DIR; do not permit path separators.
        if Path(name).name != name or name in {".", ".."}:
            raise RuntimeError(f"Unsafe refinement target name for vset output: {name!r}")
        names.append(f"{name}.vset")
    return list(dict.fromkeys(names))


def generated_vset_files_for_cleanup() -> List[str]:
    """Return known and previously generated vsets safe to remove on a clean run."""
    names = BASE_VSET_FILES + UNION_VSET_FILES + OBSOLETE_VSET_FILES
    geometry_path = SCRIPT_DIR / f"{MESH_NAME}_geometry.json"
    if geometry_path.is_file():
        try:
            names += load_target_vsets()
        except (OSError, ValueError, RuntimeError, json.JSONDecodeError):
            # A malformed old sidecar should not prevent cleanup. New geometry
            # is written during step 1 before target names are required.
            pass
    return list(dict.fromkeys(names))


def clean_generated_outputs() -> None:
    print("--> Removing generated outputs from a previous run...")
    suffixes = {
        ".poly",
        ".node",
        ".ele",
        ".face",
        ".edge",
        ".neigh",
        ".inp",
        ".uge",
        ".ugi",
        ".h5",
        ".mapping",
        ".trn",
        ".txt",
        ".xyz",
        ".csv",
        ".json",
        ".xmf",
        ".pvtp",
        ".vtp",
        ".vtu",
        ".log",
    }
    for path in SCRIPT_DIR.iterdir():
        if path.is_file() and path.name.startswith(MESH_NAME) and path.suffix in suffixes:
            path.unlink()
            print(f"    deleted {path.name}")

    for vset_name in generated_vset_files_for_cleanup():
        vset = SCRIPT_DIR / vset_name
        ex = vset.with_suffix(".ex")
        if vset.exists():
            vset.unlink()
            print(f"    deleted {vset.name}")
        if ex.exists():
            ex.unlink()
            print(f"    deleted {ex.name}")


def must_exist(path: Path, label: str, min_bytes: int = 1) -> None:
    if not nonempty(path, min_bytes=min_bytes):
        raise RuntimeError(f"{label} was not created or is empty: {path.name}")


def main() -> None:
    os.chdir(SCRIPT_DIR)
    print("\n" + "*" * 102)
    print("North Avant / Bartlesville HEC: tag-only HEC + injection borehole + three physical strainmeter sensor pods")
    print("Domain: 10 km x 10 km x 750 m; HEC: tag-only 580 m x 300 m x 5 m at (5000,5000,530) m")
    print("HEC: horizontal; long axis 5 degrees east (+x) of north (+y); material 5 tagged at z=530 m")
    print("Injection borehole: R=5 m, z=532.5--750 m, material 6")
    print("Strainmeter sensor pods: AVN2=(5160,5185,30), AVN87=(5460,5185,30), AVN31=(5350,4720,520); R=2 m, materials 7--9")
    print("All targets use local Part-1 BCC point clouds and post-mesh material tags; none is hollow or a TetGen hole.")
    print("*" * 102 + "\n")

    require_helpers()
    tetgen = require_executable(TETGEN_EXE, "TetGen")
    voronoi = require_executable(VORONOI_EXE, "VORONOI")
    if not KEEP_OLD_OUTPUTS:
        clean_generated_outputs()

    node_file = f"{MESH_NAME}.1.node"
    ele_file = f"{MESH_NAME}.1.ele"
    avs_file = f"{MESH_NAME}.inp"
    material_file = f"{MESH_NAME}_materials.txt"
    h5_file = f"{MESH_NAME}_material_ids.h5"
    uge_file = SCRIPT_DIR / f"{MESH_NAME}.uge"
    ugi_file = f"{MESH_NAME}.ugi"

    print("\n--> Step 1/9: writing PLC and running TetGen")
    build_command: List[object] = [
        sys.executable,
        SCRIPT_DIR / "build_poly_layers4.py",
        MESH_NAME,
        tetgen,
    ]
    if TETGEN_DIAGNOSE:
        build_command.append("--diagnose")
    run(build_command)

    print("\n--> Step 2/9: normalizing TetGen output")
    for suffix in (".1.node", ".1.ele", ".1.face", ".1.edge", ".1.neigh"):
        normalize_tetgen_ascii(SCRIPT_DIR / f"{MESH_NAME}{suffix}")

    print("\n--> Step 3/9: checking mesh size")
    _, tetrahedra = write_mesh_count_summary()
    if tetrahedra > MAX_TETRAHEDRA:
        raise RuntimeError(
            f"TetGen created {tetrahedra:,} tetrahedra, above the safety limit of {MAX_TETRAHEDRA:,}.\n"
            "Increase the outer BCC spacings or decrease the outer refinement radii in build_poly_layers4.py and rerun."
        )

    target_vsets = load_target_vsets()
    print("\n--> Step 4/9: material IDs, boundary tags, HEC tag, injection vset, and sensor-pod vsets")
    tag_command: List[object] = [
        sys.executable,
        SCRIPT_DIR / "layers4_get_material_boundary_tags.py",
        MESH_NAME,
    ]
    if SKIP_PX:
        tag_command.append("--skip-px")
    run(tag_command)
    for vset_name in ["hec.vset", "injection_borehole.vset", "strainmeter_sensors.vset", *target_vsets]:
        must_exist(SCRIPT_DIR / vset_name, vset_name)

    print("\n--> Step 5/9: strict TetGen -> AVS conversion and connectivity validation")
    run([sys.executable, SCRIPT_DIR / "tetgen_to_avs.py", node_file, ele_file, avs_file])
    must_exist(SCRIPT_DIR / avs_file, "AVS mesh", min_bytes=100)

    print("\n--> Step 6/9: writing PFLOTRAN material HDF5")
    run([sys.executable, SCRIPT_DIR / "material_h5_from_txt.py", node_file, h5_file, material_file])
    must_exist(SCRIPT_DIR / h5_file, "Material HDF5", min_bytes=100)

    print("\n--> Step 7/9: generating PFLOTRAN UGE with VORONOI")
    voronoi_log = SCRIPT_DIR / f"{MESH_NAME}_voronoi.log"
    run_voronoi([voronoi, "-avs", avs_file, "-type", "pflotran", "-o", uge_file.name], voronoi_log)
    must_exist(uge_file, "PFLOTRAN UGE", min_bytes=100)

    print("\n--> Step 8/9: converting vsets to PFLOTRAN .ex files")
    vset_files = list(dict.fromkeys(BASE_VSET_FILES + target_vsets + UNION_VSET_FILES))
    for vset_name in vset_files:
        vset = SCRIPT_DIR / vset_name
        if nonempty(vset):
            run([sys.executable, SCRIPT_DIR / "convert_vset_to_ex.py", uge_file.name, vset_name])
        else:
            print(f"WARNING: {vset_name} is missing or empty; skipped.")

    print("\n--> Step 9/9: generating UGI and mapping")
    run([sys.executable, SCRIPT_DIR / "generate_ugi.py", ele_file, node_file, ugi_file])
    run([sys.executable, SCRIPT_DIR / "mapping.py", MESH_NAME])

    print("\n" + "*" * 102)
    print("Workflow completed successfully.")
    print("Material 5 is the rotated tag-only HEC; material 6 is the injection cylinder; materials 7--9 are AVN2, AVN87, and AVN31 sensor pods.")
    print("*" * 102 + "\n")


if __name__ == "__main__":
    main()
